# Generated by Django 4.1.6 on 2023-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('item_type', models.CharField(choices=[('story', 'Story'), ('comment', 'Comment')], max_length=10)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
